Removes an initialization of the bIgnoreCase boolean within the declaration of the CacheFindReplaceConfig struct in Adapt_It.h. This initialization causes an error C2864 on older compilers like VS 2008 saying that only static const integral data members can be initialized within a class. The structs members are already initialized within the CFindDlg::OnRestoreFindDefaults() function which calls the App's WriteCacheDefaults() function, initializing all struct members.